FIREBASE_DB_URL = "https://herd-mentality-7c6ab-default-rtdb.firebaseio.com/"

firebase_creds = """
{
  "type": "service_account",
  "project_id": "herd-mentality-7c6ab",
  "private_key_id": "6ebe1678577245280fd3f784286e84e58ae1a215",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDhYvbMV9MhKHQV\\n...\\n-----END PRIVATE KEY-----\\n",
  "client_email": "firebase-adminsdk-fbsvc@herd-mentality-7c6ab.iam.gserviceaccount.com",
  "client_id": "113049859132367174609",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40herd-mentality-7c6ab.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
